<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('courses')->insert([
            [
                'name' => 'Introduccion a la Programacion',
                'code' => 'CS101',
                'description' => 'Introduccion a la Programacion',
                'credits' => 4,
                'teacher_id' => 2,
                'academic_period_id' => 1,
                'capacity' => 30,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Matematicas',
                'code' => 'MT101',
                'description' => 'Introduccion a la Matematicas',
                'credits' => 3,
                'teacher_id' => 3,
                'academic_period_id' => 1,
                'capacity' => 25,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Filosofia',
                'code' => 'FI101',
                'description' => 'Filosofia',
                'credits' => 3,
                'teacher_id' => 1,
                'academic_period_id' => 1,
                'capacity' => 35,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sociologia',
                'code' => 'SC101',
                'description' => 'Sociologia',
                'credits' => 4,
                'teacher_id' => 2,
                'academic_period_id' => 2,
                'capacity' => 20,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ingles',
                'code' => 'IN101',
                'description' => 'Ingles',
                'credits' => 3,
                'teacher_id' => 3,
                'academic_period_id' => 2,
                'capacity' => 25,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Matematicas 2',
                'code' => 'MATH220',
                'description' => 'Logic, sets and combinatorics',
                'credits' => 3,
                'teacher_id' => 1,
                'academic_period_id' => 2,
                'capacity' => 35,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Desarrollo de Software',
                'code' => 'MATH210',
                'description' => 'Desarrollo de Software',
                'credits' => 3,
                'teacher_id' => 1,
                'academic_period_id' => 1,
                'capacity' => 35,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Programacion Multiplataforma',
                'code' => 'PROG101',
                'description' => 'Programacion Multiplataforma',
                'credits' => 3,
                'teacher_id' => 1,
                'academic_period_id' => 1,
                'capacity' => 35,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Quimica',
                'code' => 'QU101',
                'description' => 'Quimica',
                'credits' => 3,
                'teacher_id' => 1,
                'academic_period_id' => 1,
                'capacity' => 35,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Biologia',
                'code' => 'BI101',
                'description' => 'Biologia',
                'credits' => 3,
                'teacher_id' => 1,
                'academic_period_id' => 1,
                'capacity' => 35,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
